version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sosmama_data:/app/sosmama.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped

volumes:
  sosmama_data:
